name: FireSlime
author: GKFire
api-version: 1.18
version: ${project.version}
website: https://github.com/GKFire/FireSlime
main: me.gkfiredev.fireslime.FireSlime

depend: [Slimefun]
softdepend: [ExoticGarden, ExtraGear, PrivateStorage]
